### ISSUE TITLE
"Source class "\Targetpay\Mrcash\Controller\Mrcash\Result" for "Targetpay\Mrcash\Controller\Mrcash\ResultFactory" generation does not exist.

### ISSUE THREAD

**Issue by Omitri** [idealplugins/magento2#1]
Magento 2.1.2: Using Bancontact, I'm getting the following error while cancelling the payment. 

"Source class "\Targetpay\Mrcash\Controller\Mrcash\Result" for "Targetpay\Mrcash\Controller\Mrcash\ResultFactory" generation does not exist.

I've done setup:di:compile a couple of times, but no result.

**Comment by Zazell** [comment]
We have located the issue and have just pushed an update to fix it (release 0.1.6). 
Please confirm that this fixes the issue.

**Comment by Omitri** [comment]
Thanks for the fast support, it's working now.
